// src/Pages/Company/Project/Delete.jsx
import React, { useContext, useState } from 'react';
import Modal from '../../../Components/Modal';
import { useNavigate } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Spinner from '../../../Components/Spinner/Spinner';
import { AuthContext } from '../../../Context/authContext';
import axios from '../../../axios';


const btnClasses = 'rounded-md border border-transparent bg-slate-600 px-3 py-1 text-sm text-white shadow-sm hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-slate-500 focus:ring-offset-2';
const btnCloseClasses = 'rounded-md border border-transparent bg-red-600 px-3 py-1 text-sm text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2';

const DeleteProjectButton = ({ project, onProjectDeleted }) => {
  
  const navigate = useNavigate();
  const {currentCompany} = useContext(AuthContext);
  const [show, setShow] = useState(false);
  const [inProgress, setInProgress] = useState(false);
  const [error, setError] = useState(false);

  const toggleModal = () => {
    setShow(!show);
  };


  const deleteProject = async () => {
    setInProgress(true);

    try {
        await axios.delete(`/projects/${project.id}`);
        onProjectDeleted();
        navigate(`/company/${currentCompany.id}/projects`);
    } catch (error) {
        console.log(error)
    } finally{
      setInProgress(false);
      toggleModal();
    }

  };

  return (
    <div>
      <button onClick={toggleModal} >
        <span className="flex gap-1 items-center">
            <FontAwesomeIcon icon={'fa-trash-alt'} className="text-red-600"/>
            <span>
                Delete
            </span>
        </span>
      </button>



      <Modal show={show} closeable={true} maxWidth="sm">
        {inProgress ? (
          <div className="p-6 h-36 flex justify-center items-center">
            <Spinner text="Deleting..." />
          </div>
        ) : (
          <div className="p-6">
            <div className="flex gap-2 items-center mb-3">
              <h2 className="text-red-500">Are you sure, you want to delete this Project?</h2>
            </div>

            <div className="flex gap-2">
              <button
                type="button"
                onClick={deleteProject}
                className={btnCloseClasses}
              >
                  <FontAwesomeIcon icon={'fa-trash-alt'} className="text-white"/> Yes, Delete
              </button>
              <button
                type="button"
                onClick={toggleModal}
                className={btnClasses}
              >
                No, Go Back
              </button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default DeleteProjectButton;

// src/Pages/Company/Delete.vue
<script setup>
import Modal from "@/Components/Modal.vue";
import { ref } from 'vue';
import { router } from "@inertiajs/vue3";
import Spinner from '@/Components/Spinner.vue';


const props = defineProps({
    company: {
        type: Object, 
        required: true,
    }
})

const btnClasses = 'rounded border border-transparent bg-blue-600 px-3 py-1 text-sm text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2';
const btnCloseClasses = 'rounded border border-transparent bg-red-600 px-3 py-1 text-sm text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2';
const primaryLinkClasses = 'block w-full px-4 py-2 text-start text-sm leading-5 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus:bg-gray-100 dark:focus:bg-gray-800 transition duration-150 ease-in-out flex items-center gap-1';

const inProgress = ref(false);

function deleteCompany() {

    inProgress.value= true;

    router.post(route('admin.company.destroy', props.company.id),
        {
            _method: 'delete'
        }, 
        {
            onSuccess: ()=>{
                toggleModal();
                inProgress.value = false;
            },
            preserveScroll: true,
        }
    );


}

const show = ref(false);

const toggleModal = () =>{
    show.value = !show.value
}

</script>

<template>

    <div>
        <button 
            @click="toggleModal"
            :class="primaryLinkClasses"
            class="block w-full mb-1"
            >
            <font-awesome-icon icon="fa-trash-alt"></font-awesome-icon>
            Delete
        </button>
    </div>

    <Modal :show="show" :closeable="true" :max-width="'sm'">

        <div v-if="inProgress" class="p-6 h-36 flex justify-center items-center">
            <Spinner :text="'Deleting...'"/>
        </div>


        <div v-if="!inProgress" class="p-6">
            <div class="flex gap-2 items-center mb-6">
                    <div class="h-12 w-12 rounded-full shrink-0 overflow-hidden">
                        <img :src="company.logo" class="h-full w-full object-cover" >
                    </div>
                    <div class="grow">
                        <h2 class="text-slate-500 text-xl">Delete this BMC?</h2>
                    </div>
                </div>

            <div class="flex gap-2">
                <button 
                    type="button"
                    :class="btnCloseClasses"
                    @click="deleteCompany"
                    >
                        <font-awesome-icon icon="fa-trash-alt"></font-awesome-icon>
                        Yes, Delete
                </button>
                <button 
                    type="button" 
                    :class="btnClasses"
                    @click="toggleModal"
                    >
                    No, Go Back
            </button>
            </div>
        </div>
    </Modal>

</template>
