// src/Pages/Tenant/Bill/Edit.jsx
import { useContext, useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import InputLabel from '../../../Components/InputLabel';
import TextInput from '../../../Components/TextInput';
import axios from '../../../axios';
import { AuthContext } from '../../../Context/authContext';
import Spinner from '../../../Components/Spinner/Spinner';
import TenantDashboardLayout from '../../../Layouts/TenantDashboardLayout';


const inputClasses = 'block border w-full rounded-md border-gray-300 shadow-sm focus:border-orange-500 focus:ring-orange-500 sm:text-sm p-4'
const btnClasses = 'rounded-md bg-orange-600 hover:bg-orange-700 text-white shadow-sm px-5 py-1.5 transition-all duration-300 ease-in-out';



export default function TenantBillEdit() {
    
    const {currentTenant} = useContext(AuthContext);
    const [bill, setBill] = useState();
    const [isProcessing, setIsProcessing] = useState(false);
    const [error, setError] = useState();
    
    const [inputs, setInputs] = useState({
        name: "",
        description: "",
    });


    const navigate = useNavigate();
    const location = useLocation();
    const billId = location.pathname.split('/')[3];

    
    
    useEffect(()=>{
        const fetchIssue = async () => {
                   
            try {
                const res = await axios.get(`/bills/${billId}`)

                setIssue(res.data);

                setInputs({
                    name: res.data.name || '', 
                    description: res.data.description || '',
                });

            } 
            catch (error){
            } 
    
        }
        fetchIssue()

    }, [billId])
    
    
    
    const handleInputChange = (e)=>{
        setInputs(prev => ({...prev, [e.target.name]: e.target.value}))
    }

    const submit = async (e) => {
        e.preventDefault();

        setIsProcessing(true)

        try {
            await axios.put(`/bills/${bill.id}`, inputs);
            navigate(`/company/${currentTenant.id}/bills`)
        } catch (error) {
            console.log(error)
            // setError(error.response.data)
        }

        setIsProcessing(false)

    };

    if(!bill){
        return <Spinner />
    }

    return (
        <TenantDashboardLayout>
            <div className="container mx-auto py-16">

                <div className="mb-8">
                    <Link to={`/company/${currentTenant.id}/bills`} className="rounded-md bg-orange-600 hover:bg-orange-700 pl-3 pr-4 py-2 text-white"> <font-awesome-icon icon="fa-chevron-left"></font-awesome-icon> Back</Link>
                </div>
                <div className="bg-white rounded-lg overflow-hidden">
                    <div className="relative">
                        <div className="flex gap-2 items-center bg-slate-200 rounded-t px-4 py-2">
                            <div className="py-2">
                                <h4 className="font-bold text-color-main leading-4 text-lg uppercase">Edit a bill</h4>
                            </div>
                        </div>
                    </div>
                    {isProcessing ? 
                    (<div className="p-6 h-36 flex justify-center items-center">
                        <Spinner />
                    </div>)
                    : 
                   ( <form onSubmit={submit} className='p-6'>
                    <div className="grid grid-cols-2 gap-4">

                        <div className=''>

                            <InputLabel htmlFor="name" value={'bill Name'}/>
                            <TextInput
                                id="name"
                                type="text"
                                name="name"
                                value={inputs.name}
                                className="mt-1 block w-full"
                                autoComplete="name"
                                onChange={handleInputChange}
                                required
                                placeholder="bill Name / Title"

                            />
                        </div>
                        <div className=''>
                            <InputLabel htmlFor="name" value={'Location'}/>

                            <TextInput
                                id="location"
                                name="location"
                                value={inputs.location}
                                className="mt-1 block w-full "
                                autoComplete="location"
                                onChange={handleInputChange}
                                placeholder="bill Location"
                            />
                        </div>

                        <div className="col-span-2 mb-3">
                            <InputLabel htmlFor="description" value="Description" />

                            <textarea
                                id="description"
                                name="description"
                                value={inputs.description}
                                className={inputClasses}
                                onChange={handleInputChange}
                                required
                                rows={5}
                                placeholder='Shot and Precise Description about the bill'
                            ></textarea>
                        </div>
                    </div>

                        <div className="flex gap-2">
                            <button 
                                type="submit"
                                className={`${btnClasses} ${ isProcessing && 'opacity-25' }`}
                                disabled={isProcessing}
                                >
                                    Submit
                            </button>
                        </div>
                        {
                            // error && <div className="bg-red-200 text-red-600 font-bold p-2 text-center">{error}</div>
                        }
                    </form>)
                    }

                </div>

            </div>

        </TenantDashboardLayout>
    );
}

// src/Pages/Company/Edit.vue
<script setup>
import AdminDashboardLayout from '@/Layouts/AdminDashboardLayout.vue';
import { Head } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import { useForm, router } from '@inertiajs/vue3';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import TextInput from '@/Components/TextInput.vue';
import Spinner from '@/Components/Spinner.vue';

const props = defineProps({
    company: {
        type: Object,
        required: true
    }
});


const btnClasses = 'rounded-full bg-slate-100 shadow-sm px-5 py-1.5 text-teal-600';
const inputClasses = 'block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm'

const inProgress = ref(false);

const form = useForm({
    name: props.company.name,
    email: props.company.email,
    logo: '',
    coverimage: '',
    description: props.company.description,
})

const submit = () => {

    inProgress.value= true;

    router.post(route('admin.company.update', props.company.id), {
        _method: 'PUT',
        name: form.name,
        email: form.email,
        logo: form.logo,
        coverimage: form.coverimage,
        description: form.description,
    }, {
        onSuccess: ()=>{
            inProgress.value = false;
        },
        preserveScroll: true,
    })
}


const isReadyToSubmit = computed(()=>form.name);


</script>

<template>

    <Head>
        <title>Create BMC</title>
    </Head>

    <AdminDashboardLayout>

        <div class="container mx-auto py-16">

            
            <div class="bg-white">
                <div class="relative">
                    <div class="flex gap-2 items-center bg-slate-200 rounded px-4 py-2">
                        <div class="py-2">
                            <h4 class="font-bold text-color-main leading-4 text-lg ">Create a Company</h4>
                        </div>
                    </div>
                </div>
                <div v-if="inProgress" class="p-6 h-36 flex justify-center items-center">
                    <Spinner :has-text="true"/>
                </div>
                
                <div v-if="!inProgress" class="p-6">
                    <form @submit.prevent="submit">
                        
                        <div class="grid grid-cols-2 gap-4 mb-3">
                            <div class="">
                                <InputLabel for="name" value="Name of BMC" />
                                <TextInput 
                                    id="name" 
                                    type="text" 
                                    :class="inputClasses" 
                                    v-model="form.name" 
                                    placeholder="Official Name"
                                    required />
                                <InputError class="mt-2" :message="form.errors.name" />
                            </div>
                            <div class="">
                                <InputLabel for="email" value="Email" />
                                <TextInput 
                                    id="email" 
                                    type="email" 
                                    :class="inputClasses" 
                                    v-model="form.email" 
                                    placeholder="Email Address"
                                    required />
                                <InputError class="mt-2" :message="form.errors.email" />
                            </div>
                            
                            <div class="">
                                <InputLabel for="logo" value="Logo" />
                                <input 
                                    id="logo" 
                                    type="file" 
                                    :class="inputClasses" 
                                    class="p-1 bg-slate-100"
                                    @input="form.logo = $event.target.files[0]" 
                                    />
                                <InputError class="mt-2" :message="form.errors.logo" />
                            </div>
            
                            <div class="">
                                <InputLabel for="coverimage" value="Cover Image" />
                                <input 
                                    id="coverimage" 
                                    type="file" 
                                    :class="inputClasses" 
                                    class="p-1 bg-slate-100"
                                    @input="form.coverimage = $event.target.files[0]" 
                                    />
                                <InputError class="mt-2" :message="form.errors.image" />
                            </div>
                    
                            <div class="col-span-2">
                                <InputLabel for="description" value="Description" />
                                <textarea  v-model="form.description" :class="inputClasses" placeholder="Short, precise and catchin description"></textarea>
                            </div>
                        
                        </div>
                
                        <div class="flex gap-2">
                            <button 
                                type="submit"
                                :class="[form.processing ? 'opacity-25' : btnClasses,[isReadyToSubmit ? 'bg-teal-600 text-white' : 'bg-slate-300']]"
                                @click="submit"
                                :disabled="form.processing || !isReadyToSubmit"
                                >
                                    Submit
                            </button>
                        </div>
                
                    </form>
                </div>
            </div>
            
        </div>
    </AdminDashboardLayout>
</template>
